### ISSUE TITLE
OData v2

### ISSUE THREAD

**Issue by marikaner** [jungsap/capWithS4#3]
Hello Thomas, just a tiny remark: The SAP S/4HANA Cloud SDK for JS only supports OData v2 services. The business-partner-service is also v2. :)

**Comment by jungsap** [comment]
And how is that an issue?

**Comment by marikaner** [comment]
The readme says that it is a v4 service. I should have been more precise ;)

**Comment by jungsap** [comment]
No the readme doesn't say that the SDK is OData V4. Here is exactly what it says:
**Cloud Application Programming Model Node.js OData V4 example** that uses a Remote S/4 service (via S4HANA Cloud SDK)

It says the project provides an SAP Cloud Application Programming Model Node.js Service - which absolutely is OData V4. This OData service has three entities - PO Header, PO Item, and Business Partner.  All exposed via OData V4.  The PO Header and Item are coming from a local HDI container persistence but the Business Partner is really just a proxy entity which is implemented by an exit call through the S/4 SDK.  But in the end what this project creates is a CAP based Node.js OData V4 service.

**Comment by marikaner** [comment]
Ah ok, cool, thanks for clarifying.
